version: '3'
services:
  mariadb:
    image: mariadb:10.5
    container_name: phone_directory_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phone_directory
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
